/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./static/js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-red": "#BA1A1A",
        "on-primary-container": "#93a4b8",
        "on-primary-fixed-variant": "#38485a",
        "on-tertiary-fixed": "#1c1c14",
        outline: "#74777d",
        "primary-fixed": "#d3e4fa",
        "surface-container": "#e3effe",
        "primary-fixed-dim": "#b7c8dd",
        "surface-white": "#FFFFFF",
        "tertiary-fixed": "#e5e3d6",
        "tertiary-fixed-dim": "#c8c7bb",
        "on-primary-fixed": "#0c1d2d",
        primary: "#142435",
        "tertiary-container": "#393930",
        "secondary-container": "#e0dfdf",
        "inverse-primary": "#b7c8dd",
        "surface-variant": "#d8e4f3",
        tertiary: "#23241c",
        "on-secondary-fixed": "#1a1c1c",
        "on-background": "#111d27",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d8e4f3",
        background: "#f7f9ff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#edf4ff",
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary-container": "#626363",
        "surface-dim": "#d0dbea",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dee9f8",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#47473e",
        "inverse-on-surface": "#e8f2ff",
        "on-error-container": "#93000a",
        "inverse-surface": "#26313d",
        "secondary-fixed": "#e3e2e2",
        "on-surface-variant": "#44474c",
        "on-surface": "#111d27",
        "primary-container": "#2a3a4b",
        "outline-variant": "#c4c6cc",
        "on-tertiary": "#ffffff",
        secondary: "#5d5e5f",
        "on-error": "#ffffff",
        "surface-tint": "#506072",
        "on-tertiary-container": "#a3a297",
        "on-secondary-fixed-variant": "#464747",
        "surface-bright": "#f7f9ff",
        surface: "#f7f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["IBM Plex Sans", "sans-serif"],
        body: ["IBM Plex Sans", "sans-serif"],
        label: ["IBM Plex Sans", "sans-serif"],
        sans: ["IBM Plex Sans", "sans-serif"],
      },
      boxShadow: {
        ph: "0 8px 30px rgba(27, 38, 49, 0.06)",
      },
      maxWidth: {
        "max-width": "1280px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500", letterSpacing: "0.05em" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
