import json
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

from database import db
from utils.execution_tracer import log_execution
from sqlalchemy_models import (
    AgentNotification,
    AutomationAuditLog,
    AutomationRule,
    Deal,
    PropertyMatch,
    Task,
)


class AutomationService:
    """Rule-based workflow automation service."""

    def __init__(self) -> None:
        self.logger = logging.getLogger("services.automation_service")

    @log_execution
    def _loads(self, payload: Optional[str], default):
        if not payload:
            return default
        try:
            data = json.loads(payload)
            return data
        except Exception:
            return default

    @log_execution
    def get_rules(self) -> List[Dict[str, Any]]:
        rules = AutomationRule.query.order_by(AutomationRule.created_at.desc()).all()
        output: List[Dict[str, Any]] = []
        for rule in rules:
            item = rule.to_dict()
            item["conditions"] = self._loads(rule.conditions, {})
            item["actions"] = self._loads(rule.actions, [])
            output.append(item)
        return output

    @log_execution
    def create_rule(
        self,
        name: str,
        trigger_type: str,
        conditions: Dict[str, Any],
        actions: List[Dict[str, Any]],
        enabled: bool = True,
        created_by: Optional[str] = None,
    ) -> Dict[str, Any]:
        rule = AutomationRule(
            name=name,
            trigger_type=trigger_type,
            conditions=json.dumps(conditions or {}),
            actions=json.dumps(actions or []),
            enabled=enabled,
            created_by=created_by,
        )
        db.session.add(rule)
        db.session.commit()
        return self.get_rule(rule.id)

    @log_execution
    def get_rule(self, rule_id: int) -> Dict[str, Any]:
        rule = db.session.get(AutomationRule, rule_id)
        if not rule:
            raise ValueError("Rule not found")
        payload = rule.to_dict()
        payload["conditions"] = self._loads(rule.conditions, {})
        payload["actions"] = self._loads(rule.actions, [])
        return payload

    @log_execution
    def update_rule(self, rule_id: int, **kwargs) -> Dict[str, Any]:
        rule = db.session.get(AutomationRule, rule_id)
        if not rule:
            raise ValueError("Rule not found")

        for field in ["name", "trigger_type", "enabled"]:
            if field in kwargs:
                setattr(rule, field, kwargs[field])

        if "conditions" in kwargs:
            rule.conditions = json.dumps(kwargs.get("conditions") or {})
        if "actions" in kwargs:
            rule.actions = json.dumps(kwargs.get("actions") or [])

        rule.updated_at = datetime.utcnow()
        db.session.commit()
        return self.get_rule(rule_id)

    @log_execution
    def _log_audit(
        self,
        trigger_type: str,
        status: str,
        trigger_ref: Optional[str] = None,
        rule_id: Optional[int] = None,
        details: Optional[Dict[str, Any]] = None,
    ) -> None:
        audit = AutomationAuditLog(
            rule_id=rule_id,
            trigger_type=trigger_type,
            trigger_ref=trigger_ref,
            status=status,
            details=json.dumps(details or {}),
        )
        db.session.add(audit)
        db.session.commit()

    @log_execution
    def _match_conditions(self, conditions: Dict[str, Any], context: Dict[str, Any]) -> bool:
        if not conditions:
            return True

        for key, expected in conditions.items():
            actual = context.get(key)
            if isinstance(expected, dict):
                min_v = expected.get("min")
                max_v = expected.get("max")
                if min_v is not None and (actual is None or actual < min_v):
                    return False
                if max_v is not None and (actual is None or actual > max_v):
                    return False
            else:
                if actual != expected:
                    return False
        return True

    @log_execution
    def _run_actions(self, actions: List[Dict[str, Any]], context: Dict[str, Any]) -> int:
        executed = 0

        for action in actions:
            action_type = action.get("type")
            if action_type == "create_task":
                agent_id = action.get("agent_id") or context.get("agent_id")
                if not agent_id:
                    continue
                task = Task(
                    title=action.get("title", "Automated Follow-up"),
                    description=action.get("description", "Generated by automation rule"),
                    agent_id=agent_id,
                    priority=action.get("priority", "medium"),
                    status="pending",
                    due_date=None,
                )
                db.session.add(task)
                executed += 1

            elif action_type == "notify_agent":
                agent_id = action.get("agent_id") or context.get("agent_id")
                if not agent_id:
                    continue
                notification = AgentNotification(
                    agent_id=agent_id,
                    property_match_id=context.get("property_match_id"),
                    title=action.get("title", "Automation Notification"),
                    message=action.get("message", "Automation rule triggered."),
                    notification_type="system",
                    priority=action.get("priority", "normal"),
                )
                db.session.add(notification)
                executed += 1

        if executed:
            db.session.commit()
        return executed

    @log_execution
    def _run_trigger(self, trigger_type: str, context: Dict[str, Any], trigger_ref: Optional[str] = None) -> int:
        rules = AutomationRule.query.filter_by(trigger_type=trigger_type, enabled=True).all()
        total_executed = 0

        for rule in rules:
            conditions = self._loads(rule.conditions, {})
            actions = self._loads(rule.actions, [])
            try:
                if not self._match_conditions(conditions, context):
                    continue
                executed = self._run_actions(actions, context)
                total_executed += executed
                self._log_audit(
                    trigger_type=trigger_type,
                    trigger_ref=trigger_ref,
                    rule_id=rule.id,
                    status="success",
                    details={"executed_actions": executed, "context": context},
                )
            except Exception as exc:
                db.session.rollback()
                self._log_audit(
                    trigger_type=trigger_type,
                    trigger_ref=trigger_ref,
                    rule_id=rule.id,
                    status="failed",
                    details={"error": str(exc), "context": context},
                )
        return total_executed

    @log_execution
    def handle_deal_stage_changed(self, deal: Deal, old_status: Optional[str], new_status: str) -> int:
        context = {
            "deal_id": deal.id,
            "agent_id": deal.agent_id,
            "old_status": old_status,
            "new_status": new_status,
            "offer_amount": deal.offer_amount,
        }
        return self._run_trigger("deal_stage_changed", context, trigger_ref=str(deal.id))

    @log_execution
    def process_overdue_tasks(self) -> int:
        overdue_tasks = Task.query.filter(
            Task.status.in_(["pending", "in_progress"]),
            Task.due_date.isnot(None),
            Task.due_date < datetime.utcnow(),
        ).all()

        triggered = 0
        for task in overdue_tasks:
            if task.status != "overdue":
                task.status = "overdue"
                if task.priority == "low":
                    task.priority = "medium"
                elif task.priority == "medium":
                    task.priority = "high"
                db.session.commit()

            context = {
                "task_id": task.id,
                "agent_id": task.agent_id,
                "priority": task.priority,
                "status": task.status,
            }
            triggered += self._run_trigger("task_overdue", context, trigger_ref=str(task.id))

        return triggered

    @log_execution
    def handle_high_match_score(self, match: PropertyMatch) -> int:
        if match.match_score < 0.8:
            return 0

        context = {
            "property_match_id": match.id,
            "agent_id": match.agent_id,
            "match_score": match.match_score,
            "customer_id": match.customer_id,
            "property_id": match.property_id,
        }
        return self._run_trigger("high_match_score", context, trigger_ref=str(match.id))

    @log_execution
    def test_trigger(self, trigger_type: str, context: Dict[str, Any]) -> Dict[str, Any]:
        executed = self._run_trigger(trigger_type, context, trigger_ref="test")
        return {"trigger_type": trigger_type, "executed_actions": executed}


automation_service = AutomationService()

